# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10



[[main]]
  name = "People"
  url = "people"
  weight = 20
  
[[main]]
  name = "Blog"
  url = "post"
  weight = 42


[[main]]
  name = "Publications"
  url = "publication"
  weight = 30
  
[[main]]
  name = "Projects"
  url = "/#projects" 
  weight = 41

[[main]]
  name = "Events"
  url = "event"
  weight = 50

[[main]]
  name = "Contact"
  url = "contact"
  weight = 60
